### ISSUE TITLE
Infinite output of error information

### ISSUE THREAD

**Issue by C-BJ** [rivet-lang/rivet#11]
**Rivet version:** Main
**OS:** Windows 11

* * *

```rust
fn main() {
    let x = 0;
    x++;python rivetc.py test.ri
    println("{}", x);
}
```
Infinite output：
```
test.ri:3:26: error: expected `;`, found keyword `test` 
    |
  3 |     x++;python rivetc.py test.ri
    |         
```
Output after forced exit：
```
Traceback (most recent call last):
  File "C:\Users\Austen\Desktop\rivet\rivetc.py", line 9, in <module>
    src.main(sys.argv[1:])
  File "C:\Users\Austen\Desktop\rivet\src\__init__.py", line 417, in main
    comp.build_package()
  File "C:\Users\Austen\Desktop\rivet\src\__init__.py", line 70, in build_package
    self.parse_files()
  File "C:\Users\Austen\Desktop\rivet\src\__init__.py", line 197, in parse_files
    self.source_files = parser.Parser(self).parse_pkg()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 32, in parse_pkg
    return self.parse_module_files()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 37, in parse_module_files
    source_files.append(self.parse_file(input))
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 49, in parse_file
    return ast.SourceFile(file, self.parse_decls(), self.comp.mod_sym)
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 107, in parse_decls
    decls.append(self.parse_decl())
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 473, in parse_decl
    return self.parse_fn_decl(
    left = self.parse_shift_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 737, in parse_shift_expr
    left = self.parse_additive_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 758, in parse_additive_expr
    left = self.parse_multiplicative_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 770, in parse_multiplicative_expr
    left = self.parse_unary_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 791, in parse_unary_expr
    expr = self.parse_primary_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 860, in parse_primary_expr
    elif self.tok.kind in (Kind.KeyUnsafe, Kind.Lbrace):
```

**Comment by C-BJ** [comment]
```rust
fn main() {
    let mut x = {1, 2, 3};
    println("{}", v);
}
```
```
test.ri:2:19: error: expected name, found token `,` 
    |
  2 |     let mut x = {1, 2, 3};
    |       
```
```
Traceback (most recent call last):
  File "C:\Users\Austen\Desktop\rivet\rivetc.py", line 9, in <module>
    src.main(sys.argv[1:])
  File "C:\Users\Austen\Desktop\rivet\src\__init__.py", line 417, in main
    comp.build_package()
  File "C:\Users\Austen\Desktop\rivet\src\__init__.py", line 70, in build_package
    self.parse_files()
  File "C:\Users\Austen\Desktop\rivet\src\__init__.py", line 197, in parse_files
    self.source_files = parser.Parser(self).parse_pkg()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 32, in parse_pkg
    return self.parse_module_files()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 37, in parse_module_files
    source_files.append(self.parse_file(input))
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 49, in parse_file
    return ast.SourceFile(file, self.parse_decls(), self.comp.mod_sym)
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 107, in parse_decls
    decls.append(self.parse_decl())
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 473, in parse_decl
    return self.parse_fn_decl(
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 582, in parse_fn_decl
    stmts.append(self.parse_stmt())
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 607, in parse_stmt
    right = self.parse_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 688, in parse_expr
    return self.parse_or_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 691, in parse_or_expr
    left = self.parse_and_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 698, in parse_and_expr
    left = self.parse_equality_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 705, in parse_equality_expr
    left = self.parse_relational_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 717, in parse_relational_expr
    left = self.parse_shift_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 737, in parse_shift_expr
    left = self.parse_additive_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 758, in parse_additive_expr
    left = self.parse_multiplicative_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 770, in parse_multiplicative_expr
    left = self.parse_unary_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 791, in parse_unary_expr
    expr = self.parse_primary_expr()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 872, in parse_primary_expr
    stmt = self.parse_stmt()
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 671, in parse_stmt
    self.expect(Kind.Semicolon)
  File "C:\Users\Austen\Desktop\rivet\src\parser.py", line 76, in expect
    report.error(f"expected {kstr}, found {self.tok} ", self.tok.pos)
  File "C:\Users\Austen\Desktop\rivet\src\token.py", line 312, in __str__
    if not string[0].isalpha():
KeyboardInterrupt
```
